version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /volume1/Backups/nimlab/NIMLAB_DATABASE/published_datasets:/published_datasets
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUNNING_IN_DOCKER=True

  celery_worker:
    build: .
    command: celery -A django_project worker --loglevel=info  
    volumes:
      - .:/code  # Change this to match your Django project path if different
      - /volume1/Backups/nimlab/NIMLAB_DATABASE/published_datasets:/published_datasets
    depends_on:
      - db  
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
