version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Mount custom Nginx configuration directory
      - /volume1/dataset_imports:/app/static/published_datasets
      # Mount the static volume directly into Nginx to serve static content
    depends_on:
      - web
    networks:
      - nimlab_docker_network

  web:
    build: .
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /volume1/dataset_imports:/app/static/published_datasets
    networks:
      - nimlab_docker_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUNNING_IN_DOCKER=True
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A django_project worker --loglevel=info  
    volumes:
      - .:/app  # Change this to match your Django project path if different
      - /volume1/dataset_imports:/app/static/published_datasets
      # - /volume1/Backups/nimlab/NIMLAB_DATABASE/published_datasets:/app/static/published_datasets
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - nimlab_docker_network  # Connecting to the custom network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - nimlab_docker_network  # Connecting to the custom network

networks:
  nimlab_docker_network:
    external: true
