version: '3.9'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /volume1/dataset_imports:/app/static/published_datasets
      # - /volume1/Backups/nimlab/NIMLAB_DATABASE/published_datasets:/app/static/published_datasets
    ports:
      - 8000:8000
    depends_on:
      - redis 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUNNING_IN_DOCKER=True
    networks:
      - nimlab_docker_network  # Connecting to the custom network

  celery_worker:
    build: .
    command: celery -A django_project worker --loglevel=info  
    volumes:
      - .:/app  # Change this to match your Django project path if different
      - /volume1/dataset_imports:/app/static/published_datasets
      # - /volume1/Backups/nimlab/NIMLAB_DATABASE/published_datasets:/app/static/published_datasets
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - nimlab_docker_network  # Connecting to the custom network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - nimlab_docker_network  # Connecting to the custom network

networks:
  nimlab_docker_network:
    external: true
